# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 09:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=300)),
                ('room_descpription', models.TextField()),
                ('room_accesability', models.BooleanField()),
                ('room_light', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'db_table': 'rooms',
            },
        ),
    ]
