# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_adress',
            field=models.CharField(default='NON', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_city',
            field=models.CharField(default='NON', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='room_equipment',
            field=models.TextField(default='NON', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='square',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
    ]
