# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20171202_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
