# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_room_room_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_photo',
            field=models.ImageField(upload_to='mainImages'),
        ),
    ]
