# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20171207_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dyadyushka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'maks',
            },
        ),
    ]
